image: otormaigh/android-pipelines

pipelines:
  branches:
    develop:
      - step:
          script:
            - ./envar.sh
            - ./gradlew clean build publishPlugins publish
    snapshot-*:
      - step:
          script:
            - ./envar.sh
            - ./gradlew clean build publishPlugins publish
